import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import {
  ROOT,
  localRequirePaths,
  makeManifest,
  metadataValue,
  parseUserscriptMetadata,
  readUserscript
} from './project.mjs';

const distRoot = resolve(ROOT, 'dist');
const userscript = await readUserscript();
const metadata = parseUserscriptMetadata(userscript);
const version = metadataValue(metadata, 'version');
const name = metadataValue(metadata, 'name', 'Etsy BetterSearch');
const description = metadataValue(
  metadata,
  'description',
  'Better Etsy search and Favorites filtering.'
);
const modules = localRequirePaths(userscript);

if (!version) throw new Error('Userscript @version is missing.');
if (!modules.length) throw new Error('No local BetterSearch @require modules were found.');

const platformPrelude = await readFile(resolve(ROOT, 'extension/platform-prelude.js'), 'utf8');
const backgroundSource = await readFile(resolve(ROOT, 'extension/background.js'), 'utf8');
const moduleSources = [];

for (const module of modules) {
  const source = await readFile(resolve(ROOT, module.path), 'utf8');
  moduleSources.push(`\n// ===== ${module.path} =====\n${source.trim()}\n`);
}

const contentSource = `// Generated by scripts/build.mjs from the Tampermonkey module order.\n// Do not edit dist/content.js directly.\n\n(async () => {\n'use strict';\n\n${platformPrelude.trim()}\n${moduleSources.join('\n')}\n})().catch((error) => {\n  console.error('Etsy BetterSearch extension failed to initialize.', error);\n});\n`;

const diagnosticsRoot = resolve(ROOT, 'diagnostics-extension');
const diagnosticsManifestSource = await readFile(resolve(diagnosticsRoot, 'manifest.json'), 'utf8');
const diagnosticsManifest = JSON.parse(diagnosticsManifestSource);
const diagnosticsBackground = await readFile(resolve(diagnosticsRoot, 'background.js'), 'utf8');
const diagnosticsBackgroundControls = await readFile(resolve(diagnosticsRoot, 'background-controls.js'), 'utf8');
const diagnosticsBackgroundDetachAutoExport = await readFile(resolve(diagnosticsRoot, 'background-detach-autoexport.js'), 'utf8');
const diagnosticsBackgroundSessionHealth = await readFile(resolve(diagnosticsRoot, 'background-session-health.js'), 'utf8');
const diagnosticsBackgroundStreamingExport = await readFile(resolve(diagnosticsRoot, 'background-streaming-export.js'), 'utf8');
const diagnosticsBackgroundDiscardHardening = await readFile(resolve(diagnosticsRoot, 'background-discard-hardening.js'), 'utf8');
const diagnosticsBackgroundExportResume = await readFile(resolve(diagnosticsRoot, 'background-export-resume.js'), 'utf8');
const diagnosticsHarExtraInfo = await readFile(resolve(diagnosticsRoot, 'har-extra-info.js'), 'utf8');
const diagnosticsServiceWorker = await readFile(resolve(diagnosticsRoot, 'service-worker.js'), 'utf8');
const diagnosticsTransport = await readFile(resolve(diagnosticsRoot, 'transport.js'), 'utf8');
const diagnosticsBootstrapGuard = await readFile(resolve(diagnosticsRoot, 'bootstrap-guard.js'), 'utf8');
const diagnosticsContent = await readFile(resolve(diagnosticsRoot, 'content.js'), 'utf8');
const diagnosticsControls = await readFile(resolve(diagnosticsRoot, 'controls.js'), 'utf8');
const diagnosticsExportResumeGuard = await readFile(resolve(diagnosticsRoot, 'export-resume-guard.js'), 'utf8');
const diagnosticsExportUiPolish = await readFile(resolve(diagnosticsRoot, 'export-ui-polish.js'), 'utf8');
const diagnosticsExportStreaming = await readFile(resolve(diagnosticsRoot, 'export-streaming.js'), 'utf8');
const diagnosticsControlsDetachAutoExport = await readFile(resolve(diagnosticsRoot, 'controls-detach-autoexport.js'), 'utf8');

if (!diagnosticsManifest.version) throw new Error('Diagnostics manifest version is missing.');
if (!diagnosticsManifest.permissions?.includes('debugger')) throw new Error('Diagnostics extension must declare the debugger permission.');
if (diagnosticsManifest.background?.service_worker !== 'service-worker.js') {
  throw new Error('Diagnostics manifest must use the service-worker wrapper.');
}

// Parse the final concatenated production bundle and the standalone diagnostics
// scripts before writing anything. This catches cross-module declaration
// collisions and ordinary syntax problems before CI uploads artifacts.
try {
  new Function(contentSource);
  new Function(backgroundSource);
  new Function(diagnosticsBackground);
  new Function(diagnosticsBackgroundControls);
  new Function(diagnosticsBackgroundDetachAutoExport);
  new Function(diagnosticsBackgroundSessionHealth);
  new Function(diagnosticsBackgroundStreamingExport);
  new Function(diagnosticsBackgroundDiscardHardening);
  new Function(diagnosticsBackgroundExportResume);
  new Function(diagnosticsHarExtraInfo);
  new Function(diagnosticsServiceWorker);
  new Function(diagnosticsTransport);
  new Function(diagnosticsBootstrapGuard);
  new Function(diagnosticsContent);
  new Function(diagnosticsControls);
  new Function(diagnosticsExportResumeGuard);
  new Function(diagnosticsExportUiPolish);
  new Function(diagnosticsExportStreaming);
  new Function(diagnosticsControlsDetachAutoExport);
} catch (error) {
  throw new Error(`Generated extension bundle has invalid syntax: ${error.message}`, { cause: error });
}

await rm(distRoot, { recursive: true, force: true });
await mkdir(distRoot, { recursive: true });

for (const target of ['chrome', 'firefox']) {
  const targetDir = resolve(distRoot, target);
  await mkdir(targetDir, { recursive: true });
  const manifest = makeManifest(target, { version, name, description });

  await Promise.all([
    writeFile(resolve(targetDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8'),
    writeFile(resolve(targetDir, 'content.js'), contentSource, 'utf8'),
    writeFile(resolve(targetDir, 'background.js'), `${backgroundSource.trim()}\n`, 'utf8'),
    writeFile(
      resolve(targetDir, 'BUILD_INFO.json'),
      `${JSON.stringify({ version, target, sourceModules: modules.map((item) => item.path) }, null, 2)}\n`,
      'utf8'
    )
  ]);
}

const diagnosticsDir = resolve(distRoot, 'diagnostics-chrome');
await mkdir(diagnosticsDir, { recursive: true });
const diagnosticsSourceFiles = [
  'service-worker.js',
  'background.js',
  'background-controls.js',
  'background-detach-autoexport.js',
  'background-session-health.js',
  'background-streaming-export.js',
  'background-discard-hardening.js',
  'background-export-resume.js',
  'har-extra-info.js',
  'transport.js',
  'bootstrap-guard.js',
  'content.js',
  'controls.js',
  'export-resume-guard.js',
  'export-ui-polish.js',
  'export-streaming.js',
  'controls-detach-autoexport.js'
];
await Promise.all([
  writeFile(resolve(diagnosticsDir, 'manifest.json'), `${JSON.stringify(diagnosticsManifest, null, 2)}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'background.js'), `${diagnosticsBackground.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'background-controls.js'), `${diagnosticsBackgroundControls.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'background-detach-autoexport.js'), `${diagnosticsBackgroundDetachAutoExport.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'background-session-health.js'), `${diagnosticsBackgroundSessionHealth.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'background-streaming-export.js'), `${diagnosticsBackgroundStreamingExport.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'background-discard-hardening.js'), `${diagnosticsBackgroundDiscardHardening.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'background-export-resume.js'), `${diagnosticsBackgroundExportResume.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'har-extra-info.js'), `${diagnosticsHarExtraInfo.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'service-worker.js'), `${diagnosticsServiceWorker.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'transport.js'), `${diagnosticsTransport.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'bootstrap-guard.js'), `${diagnosticsBootstrapGuard.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'content.js'), `${diagnosticsContent.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'controls.js'), `${diagnosticsControls.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'export-resume-guard.js'), `${diagnosticsExportResumeGuard.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'export-ui-polish.js'), `${diagnosticsExportUiPolish.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'export-streaming.js'), `${diagnosticsExportStreaming.trim()}\n`, 'utf8'),
  writeFile(resolve(diagnosticsDir, 'controls-detach-autoexport.js'), `${diagnosticsControlsDetachAutoExport.trim()}\n`, 'utf8'),
  writeFile(
    resolve(diagnosticsDir, 'BUILD_INFO.json'),
    `${JSON.stringify({
      version: diagnosticsManifest.version,
      versionName: diagnosticsManifest.version_name || diagnosticsManifest.version,
      target: 'chrome',
      source: 'diagnostics-extension',
      sourceFiles: diagnosticsSourceFiles,
      companionForBetterSearchVersion: version
    }, null, 2)}\n`,
    'utf8'
  )
]);

console.log(`Built Etsy BetterSearch ${version} for Chrome and Firefox.`);
console.log(`Shared modules bundled: ${modules.length}`);
console.log(`Built Etsy BetterSearch Diagnostics ${diagnosticsManifest.version_name || diagnosticsManifest.version} for Chrome.`);
