import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import {
  ROOT,
  localRequirePaths,
  makeManifest,
  metadataValue,
  parseUserscriptMetadata,
  readUserscript
} from './project.mjs';

const distRoot = resolve(ROOT, 'dist');
const userscript = await readUserscript();
const metadata = parseUserscriptMetadata(userscript);
const version = metadataValue(metadata, 'version');
const name = metadataValue(metadata, 'name', 'Etsy BetterSearch');
const description = metadataValue(
  metadata,
  'description',
  'Better Etsy search and Favorites filtering.'
);
const modules = localRequirePaths(userscript);

if (!version) throw new Error('Userscript @version is missing.');
if (!modules.length) throw new Error('No local BetterSearch @require modules were found.');

const platformPrelude = await readFile(resolve(ROOT, 'extension/platform-prelude.js'), 'utf8');
const backgroundSource = await readFile(resolve(ROOT, 'extension/background.js'), 'utf8');
const moduleSources = [];

for (const module of modules) {
  const source = await readFile(resolve(ROOT, module.path), 'utf8');
  moduleSources.push(`\n// ===== ${module.path} =====\n${source.trim()}\n`);
}

const contentSource = `// Generated by scripts/build.mjs from the Tampermonkey module order.\n// Do not edit dist/content.js directly.\n\n(async () => {\n'use strict';\n\n${platformPrelude.trim()}\n${moduleSources.join('\n')}\n})().catch((error) => {\n  console.error('Etsy BetterSearch extension failed to initialize.', error);\n});\n`;

// Parse the final concatenated bundle before writing anything. This catches
// cross-module declaration collisions and other syntax problems that checking
// each source file separately cannot detect.
try {
  new Function(contentSource);
  new Function(backgroundSource);
} catch (error) {
  throw new Error(`Generated extension bundle has invalid syntax: ${error.message}`, { cause: error });
}

await rm(distRoot, { recursive: true, force: true });
await mkdir(distRoot, { recursive: true });

for (const target of ['chrome', 'firefox']) {
  const targetDir = resolve(distRoot, target);
  await mkdir(targetDir, { recursive: true });
  const manifest = makeManifest(target, { version, name, description });

  await Promise.all([
    writeFile(resolve(targetDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8'),
    writeFile(resolve(targetDir, 'content.js'), contentSource, 'utf8'),
    writeFile(resolve(targetDir, 'background.js'), `${backgroundSource.trim()}\n`, 'utf8'),
    writeFile(
      resolve(targetDir, 'BUILD_INFO.json'),
      `${JSON.stringify({ version, target, sourceModules: modules.map((item) => item.path) }, null, 2)}\n`,
      'utf8'
    )
  ]);
}

console.log(`Built Etsy BetterSearch ${version} for Chrome and Firefox.`);
console.log(`Shared modules bundled: ${modules.length}`);
